name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          flake8 src tests
          isort --check-only src tests
          black --check src tests
      - name: Type check
        run: |
          mypy src
      - name: Unit tests
        run: |
          pytest -m "unit or integration" --maxfail=1 --disable-warnings -q
      - name: Vulnerability scan
        run: |
          pip-audit -r requirements.txt || true
